name: PvP
description: AvengeTech PvP plugin
author: sn3ak
version: 1.1.0
api: [5.0.0]
depend: [Core]
main: pvp\PvP
load: STARTUP

permissions:
 pvp.perm:
  description: Sheesh
  default: true
 pvp.staff:
  description: Oh
  default: op
 pvp.tier3:
  description: Oh
  default: op
