<?php namespace pvp\tags;

use pocketmine\utils\TextFormat;

class Structure{

	const TAG_FORMAT = [
		"AdminABOOSE" => TextFormat::RED . "Admin" . TextFormat::DARK_RED . "ABOOSE",
		"OwnerABOOSE" => TextFormat::BLUE . "Owner" . TextFormat::DARK_BLUE . "ABOOSE",
		"ABOOSE" => TextFormat::GOLD . "AB" . TextFormat::WHITE . "OO" . TextFormat::GOLD . "SE",

		"Sn3akSucks" => TextFormat::RED . "Sn3ak" . TextFormat::DARK_RED . "Sucks",
		"Maloner" => TextFormat::BLUE . "Malon" . TextFormat::RED . "er",
		"#GoodGuySn3ak" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . TextFormat::DARK_BLUE . "GoodGuy" . TextFormat::DARK_GREEN . "Sn3ak",
		"#BadGuySn3ak" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . TextFormat::DARK_RED . "BadGuy" . TextFormat::GOLD . "Sn3ak",

		"FakeDev" => TextFormat::DARK_GRAY . "Fake" . TextFormat::GOLD . "Dev",
		"RichBoi" => TextFormat::YELLOW . "Rich" . TextFormat::WHITE . "Boi",
		"#DAB" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . TextFormat::GOLD . "D" . TextFormat::YELLOW . "A" . TextFormat::RED . "B",
		"Mineman" => TextFormat::GRAY . "Mine" . TextFormat::GREEN . "man",
		"HoldThisL" => TextFormat::GOLD . "Hold" . TextFormat::YELLOW . "This" . TextFormat::DARK_RED . "L",
		"RoadToFree" => TextFormat::GRAY . "Road" . TextFormat::DARK_GRAY . "To" . TextFormat::YELLOW . "Free",
		"Clickbait" => TextFormat::DARK_RED . "Cli" . TextFormat::WHITE . "ckb" . TextFormat::DARK_RED . "ait",
		"N00b" => TextFormat::DARK_GRAY . "N" . TextFormat::GRAY . "00" . TextFormat::AQUA . "b",
		"GucciGang" => TextFormat::DARK_GREEN . "Gu" . TextFormat::RED . "c" . TextFormat::DARK_GREEN . "ci" . TextFormat::DARK_GRAY . "Gang",
		"Savage" => TextFormat::LIGHT_PURPLE . "Sa" . TextFormat::RED . "va" . TextFormat::LIGHT_PURPLE . "ge",
		"TryHard" => TextFormat::YELLOW . "Try" . TextFormat::DARK_RED . "Hard",
		"InsertTagHere" => TextFormat::AQUA . "Insert" . TextFormat::GREEN . "Tag" . TextFormat::AQUA . "Here",
		"Toxic" => TextFormat::GREEN . "Tox" . TextFormat::DARK_GREEN . "ic",
		"FreeHugs" => TextFormat::WHITE . "Free" . TextFormat::LIGHT_PURPLE . "Hugs",
		"YEET" => TextFormat::YELLOW . "YEET",
		"OOF" => TextFormat::RED . "O" . TextFormat::GOLD . "O" . TextFormat::WHITE . "F",
		"Boneless" => TextFormat::BLACK . "Bo" . TextFormat::DARK_GRAY . "ne" . TextFormat::GRAY . "le" . TextFormat::WHITE . "ss",
		"OnTheGrind" => TextFormat::GRAY . "On" . TextFormat::DARK_GRAY . "The" . TextFormat::GOLD . "Grind",

		"Melon" => TextFormat::RED . "M" . TextFormat::GREEN . "elo" . TextFormat::RED . "n",
		"HoneyMustard" => TextFormat::GOLD . "Honey" . TextFormat::YELLOW . "Mustard",
		"#Chocaholic" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . TextFormat::DARK_GRAY . "Cho" . TextFormat::GOLD . "caho" . TextFormat::DARK_GRAY . "lic",

		"TechieIsBae" => TextFormat::AQUA . "Tec" . TextFormat::GOLD . "hie" . TextFormat::WHITE . "Is" . TextFormat::RED . "Bae",
		"Sn3akIsBae" => TextFormat::DARK_AQUA . "Sn3ak" . TextFormat::BLUE . "Is" . TextFormat::DARK_BLUE . "Bae",
		"ForeverAlone" => TextFormat::WHITE . "For" . TextFormat::GRAY . "ever" . TextFormat::DARK_GRAY . "Al" . TextFormat::BLACK . "one",
		"Loner" => TextFormat::GRAY . "Loner",
		"123forGF" => TextFormat::WHITE . "123" . TextFormat::GRAY . "For" . TextFormat::LIGHT_PURPLE . "GF",
		"123forBF" => TextFormat::WHITE . "123" . TextFormat::GRAY . "For" . TextFormat::AQUA . "BF",

		"#ATFTW" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . TextFormat::AQUA . "A" . TextFormat::GOLD . "T" . TextFormat::GREEN . "FTW",
		"AvengeTechJuice" => TextFormat::AQUA . "Avenge" . TextFormat::GOLD . "Tech" . TextFormat::DARK_BLUE . "Juice",
		"ATisMyCity" => TextFormat::AQUA . "A" . TextFormat::GOLD . "T" . TextFormat::YELLOW . "is" . TextFormat::AQUA . "My" . TextFormat::GREEN . "City",
		"ATisBad" => TextFormat::AQUA . "A" . TextFormat::GOLD . "T" . TextFormat::YELLOW . "is" . TextFormat::DARK_RED . "Bad",

		"BeepBeepLettuce" => TextFormat::AQUA . "Beep" . TextFormat::GOLD . "Beep" . TextFormat::GREEN . "Lettuce",
		"AmANGERY" => TextFormat::BLACK . "Am" . TextFormat::DARK_RED . "ANG" . TextFormat::GOLD . "ERY",
		"Memz" => TextFormat::GREEN . "Mem" . TextFormat::DARK_GREEN . "z",
		"Nani" => TextFormat::DARK_RED . "Nani",
		"MemeKing" => TextFormat::GREEN . "Meme" . TextFormat::BLUE . "King",
		"MemeQueen" => TextFormat::GREEN . "Meme" . TextFormat::RED . "Queen",
		"MemeGod" => TextFormat::GREEN . "Meme" . TextFormat::YELLOW . "God",
		"#CloutGang" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . "Clout" . TextFormat::GRAY . "Gang",

		"WOAH" => TextFormat::GREEN . TextFormat::OBFUSCATED . "!" . TextFormat::RESET . TextFormat::BOLD . TextFormat::GOLD . "WOAH" . TextFormat::GREEN . TextFormat::OBFUSCATED . "!" . TextFormat::RESET,
		"RUN" => TextFormat::DARK_RED . "R" . TextFormat::GOLD . "U" . TextFormat::DARK_RED . "N",
		"#JustDoIt" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . TextFormat::RED . "Just" . TextFormat::DARK_RED . "Do" . TextFormat::RED . "It",

		"OwO" => TextFormat::GOLD . "O" . TextFormat::YELLOW . "w" . TextFormat::GOLD . "O",
		"UwU" => TextFormat::GOLD . "U" . TextFormat::YELLOW . "w" . TextFormat::GOLD . "U",
		"MaloneChan" => TextFormat::BLUE . "Malone" . TextFormat::GOLD . "Chan",
		"TechieChan" => TextFormat::AQUA . "Techie" . TextFormat::GOLD . "Chan",
		"Weeb" => TextFormat::WHITE . TextFormat::OBFUSCATED . "!" . TextFormat::RESET . TextFormat::BOLD . TextFormat::LIGHT_PURPLE . "W" . TextFormat::AQUA . "e" . TextFormat::YELLOW . "e" . TextFormat::GREEN . "b" . TextFormat::OBFUSCATED . TextFormat::WHITE . "!" . TextFormat::RESET,
		"DaWae" => TextFormat::DARK_RED . "Da" . TextFormat::RED . "Wae",
		"MYSPAGHET" => TextFormat::DARK_GRAY . "MY" . TextFormat::GOLD . "SPAGHET",
		"RawrXD" => TextFormat::GREEN . "Rawr" . TextFormat::GRAY . "XD",
		"Ezpz" => TextFormat::GREEN . "Ez" . TextFormat::AQUA . "pz",
		"Woof" => TextFormat::BLUE . "W" . TextFormat::RED . "oo" . TextFormat::BLUE . "f",
		"Meow" => TextFormat::RED . "Meow",
		"Oink" => TextFormat::LIGHT_PURPLE . "Oink",
		"Mooooo" => TextFormat::BLACK . "M" . TextFormat::WHITE . "o" . TextFormat::BLACK . "o" . TextFormat::WHITE . "o" . TextFormat::BLACK . "o" . TextFormat::WHITE . "o",

		"Useless" => TextFormat::GOLD . "Use" . TextFormat::DARK_RED . "less",
		"Potato" => TextFormat::GOLD . "Potato",
		"Spoon" => TextFormat::GRAY . "Spoon",
		"Denied" => TextFormat::DARK_RED . "Denied",
		"Kek" => TextFormat::GOLD . "K" . TextFormat::YELLOW . "e" . TextFormat::GOLD . "k",
		"LOL" => TextFormat::YELLOW . "L" . TextFormat::WHITE . "O" . TextFormat::YELLOW . "L",
		"Chugger" => TextFormat::YELLOW . "Chug" . TextFormat::GOLD . "ger",
		"Baguette" => TextFormat::GOLD . "Baguette",
		"IceJuice" => TextFormat::AQUA . "Ice" . TextFormat::WHITE . "Juice",
		"Zucc" => TextFormat::AQUA . TextFormat::OBFUSCATED . "!" . TextFormat::RESET . TextFormat::BOLD . TextFormat::AQUA . "Zucc" . TextFormat::OBFUSCATED . "!" . TextFormat::RESET,
		"FeelsBadMan" => TextFormat::GREEN . "Feels" . TextFormat::DARK_RED . "Bad" . TextFormat::DARK_GREEN . "Man",
		"#NoLife" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . TextFormat::RED . "No" . TextFormat::YELLOW . "Life",
		"KingOfAT" => TextFormat::OBFUSCATED . TextFormat::BLUE . ";" . TextFormat::AQUA . ";" . TextFormat::RESET . TextFormat::BOLD . TextFormat::YELLOW . "King" . TextFormat::WHITE . "Of" . TextFormat::AQUA . "A" . TextFormat::GOLD . "T" . TextFormat::OBFUSCATED . TextFormat::AQUA . ";" . TextFormat::BLUE . ";" . TextFormat::RESET,
		"QueenOfAT" => TextFormat::OBFUSCATED . TextFormat::DARK_PURPLE . ";" . TextFormat::LIGHT_PURPLE . ";" . TextFormat::RESET . TextFormat::BOLD . TextFormat::YELLOW . "Queen" . TextFormat::WHITE . "Of" . TextFormat::AQUA . "A" . TextFormat::GOLD . "T" . TextFormat::OBFUSCATED . TextFormat::LIGHT_PURPLE . ";" . TextFormat::DARK_PURPLE . ";" . TextFormat::RESET,

		"L" => TextFormat::ITALIC . TextFormat::GOLD . "L",
		"AMOGUS" => TextFormat::OBFUSCATED . TextFormat::WHITE . "ii" . TextFormat::RESET . TextFormat::BOLD . TextFormat::RED . "AMOGUS!" . TextFormat::OBFUSCATED . TextFormat::WHITE . "ii" . TextFormat::RESET,
		"SussyImposter" => TextFormat::RED . "Sussy" . TextFormat::AQUA . "Impostor",
		"Grape" => TextFormat::DARK_PURPLE . "Grape",
		"Bean" => TextFormat::YELLOW . "Bean",
		"Cheese" => TextFormat::GOLD . "Cheese",
		"Salad" => TextFormat::GREEN . "Salad",
		"PogChamp" => TextFormat::YELLOW . "Pog" . TextFormat::GRAY . "Champ",
		"WeirdChamp" => TextFormat::DARK_RED . "Weird" . TextFormat::GRAY . "Champ",
		"P2W" => TextFormat::BLUE . "P" . TextFormat::DARK_AQUA . "2" . TextFormat::AQUA . "W",
		"FixTPS" => TextFormat::DARK_GREEN . "Fix" . TextFormat::GREEN . "TPS",
		"BruhMoment" => TextFormat::DARK_PURPLE . "Bruh" . TextFormat::LIGHT_PURPLE . "Moment",
		"Spicy" => TextFormat::RED . "S" . TextFormat::DARK_RED . "p" . TextFormat::RED . "i" . TextFormat::DARK_RED . "c" . TextFormat::RED . "y",
		"Brazil" => TextFormat::DARK_GREEN . "Bra" . TextFormat::YELLOW . "zil",
		"USA" => TextFormat::RED . "U" . TextFormat::WHITE . "S" . TextFormat::BLUE . "A",
		"Japan" => TextFormat::WHITE . "Ja" . TextFormat::DARK_RED . "p" . TextFormat::WHITE . "an",
		"UK" => TextFormat::BLUE . "U" . TextFormat::DARK_RED . "K",
		"Scotland" => TextFormat::DARK_AQUA . "Scot" . TextFormat::WHITE . "land",
		"MineResetter" => TextFormat::GRAY . "Mine" . TextFormat::WHITE . "Resetter",
		"Grass" => TextFormat::DARK_GREEN . "Grass",
		"Fortnite" => TextFormat::BLUE . "Fortnite",
		"iForgor" => TextFormat::AQUA . "i" . TextFormat::DARK_GRAY . "Forgor",
		"iRember" => TextFormat::AQUA . "i" . TextFormat::YELLOW . "Rember",
		"DidIAsk" => TextFormat::DARK_PURPLE . "Did" . TextFormat::LIGHT_PURPLE . "IAsk",
		"SHEEESH" => TextFormat::OBFUSCATED . TextFormat::WHITE . "i" . TextFormat::RESET . TextFormat::BOLD . TextFormat::DARK_AQUA . "SHEEESH" . TextFormat::OBFUSCATED . TextFormat::WHITE . "i",
		//"DaBaby" => TextFormat::DARK_RED . "Da" . TextFormat::RED . "Baby",
		"Crazy" => TextFormat::RED . "C" . TextFormat::BOLD . TextFormat::OBFUSCATED . TextFormat::WHITE . "ii" . TextFormat::RESET . TextFormat::BOLD . TextFormat::GOLD . "r" . TextFormat::BOLD . TextFormat::OBFUSCATED . TextFormat::WHITE . "ii" . TextFormat::RESET . TextFormat::YELLOW . TextFormat::BOLD . "a" . TextFormat::OBFUSCATED . TextFormat::WHITE . "ii" . TextFormat::RESET . TextFormat::BOLD . TextFormat::GREEN . "z" . TextFormat::OBFUSCATED . TextFormat::WHITE . TextFormat::OBFUSCATED . TextFormat::WHITE . "ii" . TextFormat::RESET . TextFormat::BOLD . TextFormat::AQUA . "y",
		"MissTheRage???" => TextFormat::DARK_AQUA . "Miss" . TextFormat::BLUE . "The" . TextFormat::AQUA . "Rage" . TextFormat::GOLD . "???",
		"FEELTHERAGE" => TextFormat::YELLOW . "FEEL" . TextFormat::GOLD . "THE" . TextFormat::RED . "RAGE",
		"Cringe" => TextFormat::BLACK . "Cringe",
		"#MadCuzBad" => TextFormat::WHITE . "#" . TextFormat::GOLD . "Mad" . TextFormat::LIGHT_PURPLE . "Cuz" . TextFormat::RED . "Bad",
		"OkBoomer" => TextFormat::GRAY . "Ok" . TextFormat::DARK_PURPLE . "Boomer",
		
		//Limited edition
		"Santa" => TextFormat::WHITE . "San" . TextFormat::DARK_RED . "ta",
		"Dasher" => TextFormat::DARK_GREEN . "Das" . TextFormat::GREEN . "her",
		"Dancer" => TextFormat::YELLOW . "Dan" . TextFormat::RED . "cer",
		"Prancer" => TextFormat::GRAY . "Pran" . TextFormat::WHITE . "cer",
		"Vixen" => TextFormat::DARK_GRAY . "Vi" . TextFormat::GRAY . "xen",
		"Comet" => TextFormat::DARK_PURPLE . "Co" . TextFormat::LIGHT_PURPLE . "met",
		"Cupid" => TextFormat::GOLD . "Cup" . TextFormat::GRAY . "id",
		"Dunder" => TextFormat::DARK_AQUA . "Dun" . TextFormat::AQUA . "der",
		"Blixen" => TextFormat::AQUA . "Bli" . TextFormat::BLUE . "xen",
		"Rudolph" => TextFormat::RED . "Rud" . TextFormat::DARK_RED . "olph",

		"Lovebird" => TextFormat::DARK_RED . "Love" . TextFormat::YELLOW . "bird",
		"ILY" => TextFormat::DARK_PURPLE . "I" . TextFormat::RED . "L" . TextFormat::LIGHT_PURPLE . "Y",
		"Flirty" => TextFormat::LIGHT_PURPLE . "Fli" . TextFormat::RED . "rty",
		"Valentine" => TextFormat::DARK_PURPLE . "Val" . TextFormat::LIGHT_PURPLE . "ent" . TextFormat::RED . "ine",
		"Admirer" => TextFormat::RED . "Admir" . TextFormat::DARK_RED . "er",
		"BeMine" => TextFormat::RED . "Be" . TextFormat::LIGHT_PURPLE . "Mine",

		//Other
		"#iVoted" => TextFormat::RESET . TextFormat::WHITE . "#" . TextFormat::BOLD . "i" . TextFormat::YELLOW . "Voted",
	];

	const DISABLED_TAGS = [
		//Christmas
		"Santa",
		"Dasher",
		"Dancer",
		"Prancer",
		"Vixen",
		"Comet",
		"Cupid",
		"Dunder",
		"Blixen",
		"Rudolph",

		//Valentines
		"Lovebird",
		"ILY",
		"Flirty",
		"Valentine",
		"Admirer",
		"BeMine",

		"#iVoted",
	];

}
